### ISSUE TITLE
Create a demo RMarkdown document

### ISSUE THREAD

**Issue by wright13** [jakegross808/pacn-veg-package#10]
For demonstrating use of the PACN veg package in an RMarkdown report.

- [ ] Show how to install and load package
- [ ] Show how to load data
- [x] Try out Crosstalk (and possibly other options for interactive tables and graphs)
- [x] Include mapping code

**Comment by jakegross808** [comment]
Hi Sarah,
Sorry it has taken me so long to look at this - a lot of items to address after we last met. Hopefully this is an easy question.
I noticed when I load the pacnvegetation package, The functions in the R\spatial.R file do not seem to be loading? I'm trying to knit the skeleton.Rmd but I get error "could not find function "PlotAndTransectLocations" which is part of the "spatial.R" which I think for some reason is not loading....
