### ISSUE TITLE
rbind in memory 

### ISSUE THREAD

**Issue by jakegross808** [jakegross808/pacn-veg-package#17]
rbind seemed to be giving me issues within Understory portion of utils.R

line 365 `UnderstoryCover <- dplyr::rbind(UnderstoryLow, UnderstoryHigh)`
switched to union_all `UnderstoryCover <- dplyr::union_all(UnderstoryLow, UnderstoryHigh)`

based on this https://stackoverflow.com/questions/50357789/using-dplyr-to-bind-rows-inside-a-database

not sure if union_all is ok to use in this situation.

**Comment by wright13** [comment]
That looks like exactly what we want!
