### ISSUE TITLE
Review utils code

### ISSUE THREAD

**Issue by wright13** [jakegross808/pacn-veg-package#19]
Things to look out for:

FilterPACNVeg:
Do the current filters make sense? Should any filters be added or removed? It doesn't need to cover every column that we will ever filter by, but it should include common things and especially things we may want to use to filter the entire dataset at once (park, certification, etc) for data export purposes. Species endangered status is one that I did not include but probably should.

ReadEIPS: Do the current tables and columns make sense?

To get started, I'd suggest:
```{r}
library(pacnvegetation)
all_data <- LoadPACNVeg("pacnveg", "C:/Users/sewright/OneDrive - DOI/Data Scientist Projects/FY2021/PACN/established_invasives_BE_master_20210818.mdb")  # Replace mdb path(s)
# all_data is a list of all the dataframes that were loaded, so you can examine individual tables like so:
all_data$Understory
all_data$EIPS_data
all_data$Events_extra_QAQC_EIPS
# test out filtering on individual data tables
filtered_EIPS <- FilterPACNVeg("EIPS_data", park = "AMME")
# test out filtering on full dataset
filtered_all <- FilterPACNVeg(certified = TRUE)
```

**Comment by jakegross808** [comment]
This looks awesome!!

Yes, current filters make sense. "Certified" and "Verified" are good ones to add for full dataset filter. I guess species endangered status can be added to all tables (but I hardly ever have to filter those out).  Maybe those columns can be default removed after filter? For example, filtering capability is there but they are excluded by default in the filter function, or hidden from view if that's a thing?

EIPS tables make sense I added in the a column from the segment lookup table "Sort_Order" and renamed it "Segment" which will make it easier for me to understand and work with the data. 

This is great =)

**Comment by wright13** [comment]
Thanks!
It's up to you on the endangered status columns. And now that I'm thinking about it, Kelly may also have other plans for how she wants to handle redaction of sensitive data. Let's talk about that one a little more before adding those columns.
