### ISSUE TITLE
Fix yaml error (eval.expr)

### ISSUE THREAD

**Issue by wright13** [jakegross808/pacn-veg-package#28]
``In yaml.load(string…, error.label = error.label, ...) :Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)``

I haven't been able to reproduce this message yet - @jakegross808 next time you come across this can you take a screenshot and jot down what you were doing (knitting full doc? running single code chunk?) when it showed up?

**Comment by jakegross808** [comment]
yeah, I'm sure I was doing something weird! I'll take note if it happens again.

**Comment by jakegross808** [comment]
I got the message again. I ran the Resource_Brief.Rmd, then I closed my R studio pacnvegetation project, then I opened the R studio project and ran the line "library(pacnvegetation)" - the Resource_Brief.Rmd was open as a tab but I did not run it. 

This produced this warning message: ```
Warning messages:
1: In yaml.load(string, error.label = error.label, ...) :
  Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)
2: In yaml.load(string, error.label = error.label, ...) :
  Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)
3: In yaml.load(string, error.label = error.label, ...) :
  Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)
4: In yaml.load(string, error.label = error.label, ...) :
  Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)
5: In yaml.load(string, error.label = error.label, ...) :
  Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)
6: In yaml.load(string, error.label = error.label, ...) :
  Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)
7: In yaml.load(string, error.label = error.label, ...) :
  Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)
8: In yaml.load(string, error.label = error.label, ...) :
  Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)
9: In yaml.load(string, error.label = error.label, ...) :
  Evaluating R expressions (!expr) will soon require explicit `eval.expr` option (see yaml.load help)
> library(pacnvegetation)
```
If I run library(pacnvegetation) a second time it does not give warning

**Comment by wright13** [comment]
Looks like the `yaml` package will soon no longer be evaluating things prefaced by `!expr` by default (we're using it a bunch in the params of our rmd header section). For the moment just use `options("yaml.eval.expr" = TRUE)` at the console and that should get it to quit giving you warnings. Later we can look into setting that option when the R package loads
