### ISSUE TITLE
Plot level cover change - what will this look like when there are more than 2 sample cycles?

### ISSUE THREAD

**Issue by wright13** [jakegross808/pacn-veg-package#30]
Will we always be comparing the first year to the last year? Or the last year to the year before?

**Comment by jakegross808** [comment]
I have been thinking about this and I think we need to have both options. So if there were 5 cycles sampled I would want to be able to look at cycle 5 v 4 , and cycle 5 v 1.  I've been working on a way to have a table with a column for each comparison - for example column names 3v2, 3v1, and 2v1 so you could easily switch the input to graph the different column (year span).

**Comment by jakegross808** [comment]
Currently the `UnderNativityCover()` function which makes the table for the change graph uses a lag to calculate change from selected cycle to the previous cycle:

`UnderNativityCover(combine_strata = TRUE, paired_change = TRUE, sample_frame = "Olaa")`

**Comment by jakegross808** [comment]
But I don't have it set up to calculate change between most recent cycle and first cycle yet.

**Comment by wright13** [comment]
I can set that up

**Comment by wright13** [comment]
For the moment, I've got it set up so that you can pass any two cycle numbers to UnderNativityCover and calculate change between the two. This should set us up to be able to modify it at some point to compare every cycle to all previous cycles. We should think through that though, because the number of columns will grow faster with each new cycle.
