### ISSUE TITLE
enquos() and !!! - Quote and unquote multiple arguments

### ISSUE THREAD

**Issue by jakegross808** [jakegross808/pacn-veg-package#33]
I am struggling with `group_by` inside a function.

I want to feed different column names into group-by based on a user supplied variable `test_summary_variable`

I'm starting with a list called `test_grouping_vars` and then appending new columns to that list depending on what summary variable is selected. However, I can't seem to find the right syntax to express the grouping variables correctly:

`test_raw_data <- FilterPACNVeg("Understory", sample_frame = "Olaa", is_qa_plot = FALSE)

test_summary_variable = "Nativity"
test_grouping_vars <- c("Unit_Code", "Sampling_Frame", "Cycle", "Year", "Plot_Type", "Plot_Number", "Point", "Stratum")

if (test_summary_variable == "Nativity") {
  test_grouping_vars <- append(test_grouping_vars, "Nativity")
}

if (test_summary_variable == "Life_Form") {
  test_grouping_vars <- append(test_grouping_vars, c("Nativity", "Life_Form"))
}

if (test_summary_variable == "Species") {
  test_grouping_vars <- append(test_grouping_vars, c("Nativity", "Life_Form", "Code", "Scientific_Name"))
}

test_grouping_vars <- enquos(test_grouping_vars)

test_Nat_Cov <- test_raw_data %>%
  dplyr::group_by(!!!test_grouping_vars) %>%
  dplyr::summarise(Hits_All_Nat = dplyr::n(), .groups = 'drop')`

`Error: Problem adding computed columns in `group_by()`.
x Problem with `mutate()` input `..1`.
i `..1 = <chr>`.
i `..1` must be size 29487 or 1, not 9.
Run `rlang::last_error()` to see where the error occurred.`

**Comment by jakegross808** [comment]
```
test_raw_data <- FilterPACNVeg("Understory", sample_frame = "Olaa", is_qa_plot = FALSE)


test_summary_variable = "Nativity"
test_grouping_vars <- c("Unit_Code", "Sampling_Frame", "Cycle", "Year", "Plot_Type", "Plot_Number", "Point", "Stratum")

if (test_summary_variable == "Nativity") {
  test_grouping_vars <- append(test_grouping_vars, "Nativity")
}

if (test_summary_variable == "Life_Form") {
  test_grouping_vars <- append(test_grouping_vars, c("Nativity", "Life_Form"))
}

if (test_summary_variable == "Species") {
  test_grouping_vars <- append(test_grouping_vars, c("Nativity", "Life_Form", "Code", "Scientific_Name"))
}

test_grouping_vars <- enquos(test_grouping_vars)

test_Nat_Cov <- test_raw_data %>%
  dplyr::group_by(!!!test_grouping_vars) %>%
  dplyr::summarise(Hits_All_Nat = dplyr::n(), .groups = 'drop')
```

**Comment by jakegross808** [comment]
After some more reading I think I need to use vars(Unit_Code, Sampling_Frame, etc) instead of c("Unit_Code", "Sampling_Frame", etc). 

However, I'm not sure how to append an item to a vars() list... I think I just need to understand the vars() object better

**Comment by wright13** [comment]
Oh man I struggle with this every time I have to do it. Let me see if I can dig up some example code from another package...

**Comment by wright13** [comment]
Ah try this:
`dplyr::group_by(dplyr::across(test_grouping_vars))`

**Comment by wright13** [comment]
And you can just use `c(test_grouping_vars, "Nativity")` instead of append if you want to keep it a little simpler to read

**Comment by jakegross808** [comment]
interesting... that's much cleaner than the solution I just found to append a vars list:
`test_grouping_vars <- vars(!!!test_grouping_vars, Nativity, Life_Form)`

**Comment by wright13** [comment]
Yeah I think the across() thing was added in a relatively recent version of dplyr. I'm pretty sure I've used vars in the past as well. I think it also depends on whether you want your function to accept grouping vars as a character vector or as unquoted column names (like tidyverse functions do). Either way works fine, so I'd go with whatever you think will be more user-friendly.

**Comment by jakegross808** [comment]
Agreed. Just incase I need to look back at this for help, these two approaches give the same result but `across `is the most recent/preferred way.

**across**:
```
test_raw_data <- FilterPACNVeg("Understory", sample_frame = "Olaa", is_qa_plot = FALSE)

test_summary_variable = "Life_Form"

test_grouping_vars <- c("Unit_Code", "Sampling_Frame", "Cycle", "Year", "Plot_Type", "Plot_Number", "Point", "Stratum")

if (test_summary_variable == "Nativity") {
  test_grouping_vars <- c(test_grouping_vars, "Nativity")
}

if (test_summary_variable == "Life_Form") {
  test_grouping_vars <- c(test_grouping_vars, c("Nativity", "Life_Form"))
}

if (test_summary_variable == "Species") {
  test_grouping_vars <- c(test_grouping_vars, c("Nativity", "Life_Form", "Code", "Scientific_Name"))
}

test_Nat_Cov <- test_raw_data %>%
  dplyr::group_by(dplyr::across(test_grouping_vars)) %>%
  dplyr::summarise(Hits_All_Nat = dplyr::n(), .groups = 'drop')
```

**!!!**
```
test_raw_data <- FilterPACNVeg("Understory", sample_frame = "Olaa", is_qa_plot = FALSE)

test_summary_variable = "Life_Form"

test_grouping_vars <- vars(Unit_Code, Sampling_Frame, Cycle, Year, Plot_Type, Plot_Number, Point, Stratum)

if (test_summary_variable == "Nativity") {
  test_grouping_vars <- vars(!!!test_grouping_vars, Nativity)
}

if (test_summary_variable == "Life_Form") {
  test_grouping_vars <- vars(!!!test_grouping_vars, Nativity, Life_Form)
}

if (test_summary_variable == "Species") {
  test_grouping_vars <- vars(!!!test_grouping_vars, Nativity, Life_Form, Code, Scientific_Name)
}

test_Nat_Cov <- test_raw_data %>%
  dplyr::group_by(!!!test_grouping_vars) %>%
  dplyr::summarise(Hits_All_Nat = dplyr::n(), .groups = 'drop')
```

**Comment by jakegross808** [comment]
Well... running into similar issue but this time with tidyr::complete() (https://tidyr.tidyverse.org/reference/complete.html)

I want to pass a variable with column names into this function, but it looks like across only works inside dplyr verbs. And I guess complete is not a dplyr verb. 

Any ideas?

Here is example:
```
tidyr::complete(tidyr::nesting(Unit_Code, Sampling_Frame, Plot_Type, Plot_Number, Year, Cycle, Stratum), 
                    vars(new_vars),
                    fill = list(tot_pct_cov = 0)) 
```

Here is entire code with hard coded `complete()` function:

```
Cover_test <- function(plant_grouping) {
  
  understory <- FilterPACNVeg("Understory", sample_frame = "Olaa", is_qa_plot = FALSE)
  
  understory2 <- understory %>%
    mutate(Cycle = as.factor(Cycle),
           Plot_Number = as.factor(Plot_Number),
           Stratum = replace_na(Stratum, "No_Veg"),
           Nativity = replace_na(Nativity, "No_Veg"),
           Life_Form = replace_na(Life_Form, "No_Veg"),
           Code = replace_na(Code, "No_Veg"),
           Scientific_Name = replace_na(Scientific_Name, "No_Veg"))
  
  all_vars <- c("Unit_Code", "Sampling_Frame", "Cycle", "Year",
                "Plot_Type", "Plot_Number", "Point", "Stratum")
  
  if (plant_grouping == "All") {
    new_vars <- c()
  }
  
  if (plant_grouping == "Nativity") {
    new_vars <- c("Nativity")
  }
  
  if (plant_grouping == "Life_Form") {
    new_vars <- c("Nativity", "Life_Form")
  }
  
  if (plant_grouping == "Species") {
    new_vars <- c("Nativity", "Life_Form", "Code", "Scientific_Name")
  }
  
  all_vars <- c(all_vars, new_vars)
  all_vars_minus_point <- all_vars[all_vars != "Point"]
  #all_vars_minus_point_stratum <- all_vars_minus_point[all_vars_minus_point != "Stratum"]
  
  arrange_remove <- c("Cycle", "Year", "Point")
  arrange_vars <- all_vars[!all_vars %in% arrange_remove]
  
  #new_vars_plus_stratum <- c("Stratum", new_vars)
  
  understory3 <- understory2 %>%
    dplyr::group_by(dplyr::across(all_vars)) %>%
    dplyr::summarise(Hits = dplyr::n(), .groups = 'drop') %>%
    # group hits by plot (remove Point from grouping variable)
    dplyr::group_by(dplyr::across(all_vars_minus_point)) %>%
    # Total hits at each point for each strata for entire plot
    #   (can be > 300 points or >100% because more than one native species can be present per point)
    dplyr::summarise(Cover = (sum(Hits)) / 300 * 100, .groups = 'drop')
  
  understory4 <- understory3 %>%
    # Insert "0" for cover if category does not exist (for example no hits for non-natives in High Stratum)
    tidyr::complete(tidyr::nesting(Unit_Code, Sampling_Frame, Plot_Type, Plot_Number, Year, Cycle), Stratum, Nativity,
                    fill = list(tot_pct_cov = 0)) %>%
    # Arrange table so that difference in cover between cycles can be calculated easily (example - cycle 1 value for
    #   cover is followed by cycle 2 value for cover).
    dplyr::group_by(dplyr::across(arrange_vars)) %>%
    dplyr::arrange(Cycle, Year, .by_group = TRUE) %>%
    dplyr::ungroup()
  
  return(understory4)
}
test_Nat <- Cover_test(plant_grouping = "Nativity")

```

**Comment by wright13** [comment]
Are you able to get it to work at all with the `!!!vars()` syntax? If it works, I'd use that. This stackoverflow post might be helpful too, although they're passing their additional variables in using `...` instead of a character vector.

**Comment by wright13** [comment]
Looks like `!!rlang::sym(nesting_vars)` might also do the trick

**Comment by wright13** [comment]
Someday I will learn how this actually works instead of blindly searching stackoverflow every single time it comes up 🙃

**Comment by jakegross808** [comment]
When I try `tidyr::nesting(!!!new_vars)`

I get 
```
 Error: Join columns must be present in data.
x Problem with `"Nativity"`.
```

rlang::last_error()
```
<error/rlang_error>
Join columns must be present in data.
x Problem with `"Nativity"`.
Backtrace:
  1. global::Cover_test(plant_grouping = "Nativity")
  7. tidyr:::complete.data.frame(...)
  9. dplyr:::full_join.data.frame(full, data, by = names(full))
 10. dplyr:::join_mutate(...)
 11. dplyr:::join_cols(...)
 12. dplyr:::standardise_join_by(by, x_names = x_names, y_names = y_names)
 13. dplyr:::check_join_vars(by$y, y_names)
Run `rlang::last_trace()` to see the full context.
```

**Comment by jakegross808** [comment]
...But the Nativity column is present in the data.... Might have to discuss over teams tomorrow.

**Comment by jakegross808** [comment]
`tidyr::nesting(!!rlang::sym(new_vars)))` seems to work with one string in the new_vars vector. But if there is more than one it says: 
`Error: Only strings can be converted to symbols`

```
<error/rlang_error>
Only strings can be converted to symbols
Backtrace:
  1. global::Cover_test(plant_grouping = "Life_Form")
 17. rlang::sym(new_vars)
Run `rlang::last_trace()` to see the full context.
```

**Comment by wright13** [comment]
Hmm yeah let's take a look at it tomorrow. If you can push your code when you wrap up today, I can try to take a look in the morning

**Comment by jakegross808** [comment]
Ok, I pushed this to a new branch called "Cover" - the file is in draft_scripts folder called "Cover_Function_test.R"

**Comment by wright13** [comment]
I think I got it working! I also merged my branch into yours so you've got my latest changes as of now

**Comment by jakegross808** [comment]
Yes, that works. Solution:
```
var_nest1 <- c("Unit_Code", "Sampling_Frame", "Cycle", "Year", "Plot_Type", "Plot_Number")
var_nest2 <- c("Stratum", new_vars)

tidyr::complete(tidyr::nesting(!!!rlang::syms(var_nest1)),
                    tidyr::nesting(!!!rlang::syms(var_nest2)),
                    fill = list(Cover = 0))
```
