### ISSUE TITLE
Show transect lines on map

### ISSUE THREAD

**Issue by wright13** [jakegross808/pacn-veg-package#34]

**Comment by wright13** [comment]
@jakegross808 I think I've just about got the transect lines working. A couple questions: for fixed transects, does it make sense to just use the image point coords from the latest cycle to create the transect line? Also, do we want to be able to show the actual image points or just the transect lines?

**Comment by jakegross808** [comment]
Yes, just latest cycle is good. Otherwise it will look too messy I'm thinking because they likely wouldn't line up perfectly cycle to cycle. Just the line should be fine (rather than points) as long as the line can be thick enough to see the color on it. Thanks!
