### ISSUE TITLE
Cross-talk highlighting and reset

### ISSUE THREAD

**Issue by jakegross808** [jakegross808/pacn-veg-package#41]
I've noticed that the highlight capabilities between the graph and map using crosstalk do not display as expected. Is there additional specifications needed? Point selected on graph use to highlight on map (and vice versa)- but now does not seem to work. Also is there button to reset after selection has been made?

![image](https://user-images.githubusercontent.com/80367232/176027370-6b265e76-0017-4bb9-8b35-acffc7140795.png)

**Comment by wright13** [comment]
Or maybe I'm crazy and it never worked. In any case, it should be fixed now and the changes are pushed. I added a bullet point in the rmd with instructions for selecting and deselecting points. I'm not sure if there's a way to get it to work in the opposite direction (by selecting a plot in the map to get it to highlight a point in the graph) but I can look into it if you would like that funcitonality.

**Comment by jakegross808** [comment]
It did work before, but I recall it being somewhat buggy. I think I tried to fix the bug at one point and likely just broke the functionality altogether. It would be great if it could work oppositely as well - but not a deal breaker if cannot!
