### ISSUE TITLE
Applying static color palette to leaflet map

### ISSUE THREAD

**Issue by jakegross808** [jakegross808/pacn-veg-package#42]
I'm having difficultly applying a static color palette to MapCoverTotal() function  (I just pushed this function to Cover branch and made changes to "Resource_Brief_haleakala.Rmd" so it crosstalks with UnderNativityCover.plot.nat_v_non -> totalCover_plotly to produce image below.

totalCover_plotly does the palette correctly. That is, the palette is static and does not change with data. I think this is because plot_ly does this somehow with plot_ly(colors = pal). 

However MapCoverTotal() spreads the palette across whatever data is supplied. For example, see figure below: In the map there should only be one red point to correspond with the red point in the graph.  But there are several red points because it is spreading ramp across the entire dataset instead of using a specific color for each value. Lines 304-318 within spatial.R -> MapCoverTotal()

![image](https://user-images.githubusercontent.com/80367232/176283221-aeadbf69-0848-46b9-ba0b-17ece5aeb080.png)

**Comment by wright13** [comment]
Just pushed the fix to Cover - let me know if it looks right to you.
